

GET http://localhost:8080/api/v1/eatwell/ingredient/19400?amount=100&unit=g

###

GET http://localhost:8080/api/v1/eatwell/ingredient/19400

###

GET http://localhost:8080/api/v1/eatwell/ingredient/units

###

GET http://localhost:8080/api/v1/eatwell/ingredient/

###

GET http://localhost:8080/api/v1/eatwell/ingredient/1077?unit=g&amount=500

###

GET http://localhost:8080/api/v1/eatwell/ingredient/q?query=apple

###
GET http://localhost:8080/api/v1/eatwell/calculator/12/

###
POST http://localhost:8080/api/v1/eatwell/calculator/
Content-Type: application/json

{
  "id": 12,
  "bodyMassInKg": 94,
  "heightInCm": 179,
  "age": 41,
  "activityRatio": 1.2,
  "strategy": "Complete",
  "man": true,
  "goal": "Reduction"
}

###
GET http://localhost:8080/api/v1/eatwell/calculator/

###
GET http://localhost:8080/api/v1/eatwell/calculator/12/ingredient
Content-Type: application/json

{
  "id": 1077,
  "unit": "g",
  "amount": 500
}

###
GET http://localhost:8080/api/v1/eatwell/calculator/12/recipe
Content-Type: application/json

[
{
  "id": 1082,
  "unit": "g",
  "amount": 500
},
  {
    "id": 9040,
    "unit": "large",
    "amount": 1
  },
  {
    "id": 9003,
    "unit": "medium",
    "amount": 1
  }
]