

GET http://localhost:8080/api/v1/eatwell/ingredient/19400?amount=100&unit=g

###

GET http://localhost:8080/api/v1/eatwell/ingredient/19400

###

GET http://localhost:8080/api/v1/eatwell/ingredient/units

###

GET http://localhost:8080/api/v1/eatwell/ingredient/

###

GET http://localhost:8080/api/v1/eatwell/ingredient/5062

###

GET http://localhost:8080/api/v1/eatwell/ingredient/q?query=brocco

###
GET http://localhost:8080/api/v1/eatwell/calculator/12/

###
POST http://localhost:8080/api/v1/eatwell/calculator/
Content-Type: application/json

{
  "id": 12,
  "bodyMassInKg": 70,
  "heightInCm": 170,
  "age": 27,
  "activityRatio": 1.5,
  "strategy": "Complete",
  "man": true,
  "goal": "IntenseMass"
}

###

###
GET http://localhost:8080/api/v1/eatwell/calculator/